version: '2'

services:

  rancher-server:
    image: rancher/server:v1.1.0
    restart: always
    ports:
      - "8080:8080"
    networks:
      rancher:

  rancher-helper:
    image: rancher/agent:v1.0.2
    depends_on:
      - rancher-server
    privileged: true
    volumes:
      - ./register-and-run.sh:/register-and-run.sh
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/rancher:/var/lib/rancher
    entrypoint: "/bin/bash /register-and-run.sh"
    networks:
      rancher:

networks:
  rancher:
